### ISSUE TITLE
runQuery command not available

### ISSUE THREAD

**Issue by francotiveron** [influxdata/vsflux#401] opened 2022-05-21 22:57 UTC
After installing the extension, the runQuery command is not available

![image](https://user-images.githubusercontent.com/8280970/169671497-b7478ab2-a64b-45e4-a884-9c91228ca775.png)

![image](https://user-images.githubusercontent.com/8280970/169671427-12ea7fc6-0981-4c4e-b9c0-2a75dcdd87da.png)

![image](https://user-images.githubusercontent.com/8280970/169671553-edcc0497-66d6-4cb7-9020-d01a855f7c75.png)

![image](https://user-images.githubusercontent.com/8280970/169671370-69483bed-7677-428b-a35d-ae270847abfb.png)

![image](https://user-images.githubusercontent.com/8280970/169671460-56e7491f-51c2-473c-a513-8d881052ae17.png)

![image](https://user-images.githubusercontent.com/8280970/169671486-0d575ecb-4d6a-48fa-ac29-f57ed27037c3.png)

**Comment by aleksander-ivanov** [comment] 2022-05-24 19:28
The same for me,
in previous version it worked, but after update to the last version there is no run query command.

**Comment by aleksander-ivanov** [comment] 2022-05-24 19:44
UDP:
Now we need to use F5 key only, check [commit](https://github.com/influxdata/vsflux/pull/385/commits/c9ebe6f7acf81105b7271e63735ede35e4174a3f)
@vsflux team, it wasn't clear guys, it must be in the context menu and in the command pallete.

**Comment by rockstar** [comment] 2022-07-08 04:35
Closing as working by design.

**Closed by rockstar** 2022-07-08 04:35 UTC
