### ISSUE TITLE
Add the ability to browse InfluxDB resources from the plugin

### ISSUE THREAD

**Issue by russorat** [influxdata/vsflux#265] opened 2021-08-10 17:36 UTC
I was using AWS plugin in vs code, and they have a "resource browser" for finding resources in aws.

something like this would be very handy for the vscode plugin in my opinion. the ability to browse tasks and other relevant resources in the influxdb instance. You could connect to an influxdb instance, browse for the task you needed to update, download it locally, update, test, and then save it back to the instance. 

all this could be done via the apis.

this issue would replace the existing browse instance capability with something like this:

```
influxdb instance
 - Buckets
   - Bucket 1
     - Measurement 1
       - Field 1
       - Field 2 
     - Measurement 2 
   - Bucket 2
 - Tasks
   - Task 1
   - Task 2
 ```

Clicking on a resource would give you the option to download it locally, it would then open in a file on your machine. A user could update as needed. when they are finished, they could click on the same resource and select "Update..." there they could choose the file they have just been making changes to.

**Comment by rockstar** [comment] 2021-08-14 03:13
Dupe of #261

**Closed by rockstar** 2021-08-14 03:13 UTC
Labels: enhancement
