### ISSUE TITLE
Connection incorrectly classified as not supported in cloud

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/vsflux#363] opened 2022-01-06 19:26 UTC
v0.6.13 
The extension isn't recognizing my connection as a Cloud connection. 
URL/region: https://us-west-2-1.aws.cloud2.influxdata.com/

<img width="1448" alt="Screen Shot 2022-01-06 at 1 22 52 PM" src="https://user-images.githubusercontent.com/30506042/148439690-fd32bafc-0f5d-48ed-8495-9e2e399c5641.png">
<img width="1710" alt="Screen Shot 2022-01-06 at 1 23 13 PM" src="https://user-images.githubusercontent.com/30506042/148439699-29066843-bf60-4273-b8d7-ec61a369c240.png">

queries are successful, test connection is successful. 

Thank you.

**Comment by rockstar** [comment] 2022-02-10 00:42
Is this an old connection maybe? Could you try removing it and adding it back? My personal account is using this same cloud environment and I can't reproduce.

**Comment by rockstar** [comment] 2022-02-10 00:43
Ooh! It could _also_ be that you have a token that doesn't allow access to scripts. Could you maybe issue a new token with explicit support for script access?

**Comment by rockstar** [comment] 2022-03-17 20:12
Closing as this is working as expected. If you find that the issue is still occurring, please feel free to re-open.

**Closed by rockstar** 2022-03-17 20:12 UTC
